name: Deploy to AWS Lambda with S3

on:
  push:
    branches:
      - main

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Node.js
        uses: actions/setup-node@v3
        with:
          node-version: "22"

      - name: Install dependencies
        run: npm install

      - name: Zip Lambda function
        run: zip -r function.zip . -x "*.git*" "*.github*" "*.md" ".env" "config/*" "*.lambdaignore" "test.js" "output/*"

      - name: Upload Zip to S3
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          LAMBDA_CODE_BUCKET: ${{ secrets.LAMBDA_CODE_BUCKET }}
        run: |
          aws s3 cp function.zip s3://$LAMBDA_CODE_BUCKET/function.zip

      - name: Deploy Lambda function
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_REGION: ${{ secrets.AWS_REGION }}
          LAMBDA_ROLE_ARN: ${{ secrets.LAMBDA_ROLE_ARN }}
          LAMBDA_CODE_BUCKET: ${{ secrets.LAMBDA_CODE_BUCKET }}
          LAMBDA_NAME: ${{vars.LAMBDA_NAME}}
        run: |
          aws lambda update-function-code --function-name $LAMBDA_NAME \
            --s3-bucket $LAMBDA_CODE_BUCKET \
            --s3-key function.zip || \
          aws lambda create-function --function-name $LAMBDA_NAME \
            --runtime nodejs16.x \
            --role $LAMBDA_ROLE_ARN \
            --handler index.handler \
            --code S3Bucket=$LAMBDA_CODE_BUCKET,S3Key=function.zip
